package dev.taufeeqahmed.servicepulse.history;

import java.nio.file.Path;
import java.sql.DriverManager;
import java.time.Instant;

import dev.taufeeqahmed.servicepulse.ServicePulseApplication;
import dev.taufeeqahmed.servicepulse.checking.HealthCheckResponse;
import dev.taufeeqahmed.servicepulse.checking.HealthStatus;
import dev.taufeeqahmed.servicepulse.checking.CheckResultService;
import dev.taufeeqahmed.servicepulse.incidents.IncidentRepository;
import dev.taufeeqahmed.servicepulse.incidents.IncidentStatus;
import dev.taufeeqahmed.servicepulse.registration.MonitoredService;
import dev.taufeeqahmed.servicepulse.registration.MonitoredServiceRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

import static org.assertj.core.api.Assertions.assertThat;

class CheckHistoryPersistenceTest {

    @TempDir
    Path directory;

    @Test
    void upgradesExistingDatabaseWithSafeDefaultsAndPreservesHistory() throws Exception {
        Path database = directory.resolve("legacy");
        String url = "jdbc:h2:file:" + database.toAbsolutePath().toString().replace('\\', '/');
        try (var connection = DriverManager.getConnection(url, "sa", "");
                var sql = connection.createStatement()) {
            sql.execute("CREATE TABLE monitored_services (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(255) NOT NULL, url VARCHAR(2048) NOT NULL)");
            sql.execute("INSERT INTO monitored_services (id,name,url) VALUES (1,'Existing','http://localhost/health')");
            sql.execute("CREATE TABLE health_checks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "service_id BIGINT NOT NULL REFERENCES monitored_services(id), status VARCHAR(4) NOT NULL, "
                    + "http_status INTEGER, response_time_ms BIGINT NOT NULL, checked_at TIMESTAMP WITH TIME ZONE NOT NULL)");
            sql.execute("INSERT INTO health_checks VALUES (1,1,'DOWN',503,25,TIMESTAMP WITH TIME ZONE '2026-10-03 10:00:00Z')");
        }
        try (var upgraded = start(database)) {
            var service = upgraded.getBean(MonitoredServiceRepository.class).findById(1L).orElseThrow();
            assertThat(service.getFailureThreshold()).isEqualTo(3);
            assertThat(service.getConsecutiveFailures()).isZero();
            assertThat(service.getWebhookUrl()).isNull();
            assertThat(upgraded.getBean(CheckHistoryService.class).history(1).orElseThrow())
                    .singleElement().satisfies(check -> assertThat(check.status()).isEqualTo(HealthStatus.DOWN));
        }
    }

    @Test
    void retainsRegistrationsAndHistoryAcrossApplicationRestarts() {
        Path database = directory.resolve("servicepulse");
        Instant checkedAt = Instant.parse("2026-09-28T22:30:00Z");
        long serviceId;
        try (var first = start(database)) {
            var service = first.getBean(MonitoredServiceRepository.class)
                    .save(new MonitoredService("Stored service", "https://example.com"));
            serviceId = service.getId();
            first.getBean(CheckHistoryService.class).record(service,
                    new HealthCheckResponse(serviceId, service.getName(), service.getUrl(),
                            HealthStatus.UP, 200, 123, checkedAt));
        }

        try (var restarted = start(database)) {
            assertThat(restarted.getBean(MonitoredServiceRepository.class).findById(serviceId))
                    .isPresent();
            var history = restarted.getBean(CheckHistoryService.class);
            assertThat(history.history(serviceId).orElseThrow()).singleElement().satisfies(check -> {
                assertThat(check.serviceId()).isEqualTo(serviceId);
                assertThat(check.status()).isEqualTo(HealthStatus.UP);
                assertThat(check.httpStatus()).isEqualTo(200);
                assertThat(check.responseTimeMs()).isEqualTo(123);
                assertThat(check.checkedAt()).isEqualTo(checkedAt);
            });
            var stats = history.stats(serviceId).orElseThrow();
            assertThat(stats.totalChecks()).isEqualTo(1);
            assertThat(stats.uptimePercentage()).isEqualByComparingTo("100.00");
        }
    }

    @Test
    void retainsFailureStreakAndIncidentLifecycleAcrossRestarts() {
        Path database = directory.resolve("incidents");
        long serviceId;
        long incidentId;
        try (var first = start(database)) {
            var service = first.getBean(MonitoredServiceRepository.class)
                    .save(new MonitoredService("Persistent", "http://localhost/health"));
            serviceId = service.getId();
            record(first, serviceId, HealthStatus.DOWN);
            record(first, serviceId, HealthStatus.DOWN);
            assertThat(first.getBean(IncidentRepository.class).count()).isZero();
        }
        try (var second = start(database)) {
            assertThat(second.getBean(MonitoredServiceRepository.class).findById(serviceId).orElseThrow()
                    .getConsecutiveFailures()).isEqualTo(2);
            record(second, serviceId, HealthStatus.DOWN);
            var incident = second.getBean(IncidentRepository.class).findAll().getFirst();
            assertThat(incident.getStatus()).isEqualTo(IncidentStatus.OPEN);
            incidentId = incident.getId();
        }
        try (var third = start(database)) {
            record(third, serviceId, HealthStatus.DOWN);
            assertThat(third.getBean(IncidentRepository.class).count()).isEqualTo(1);
            record(third, serviceId, HealthStatus.UP);
        }
        try (var fourth = start(database)) {
            assertThat(fourth.getBean(IncidentRepository.class).findById(incidentId)).get().satisfies(incident -> {
                assertThat(incident.getStatus()).isEqualTo(IncidentStatus.RESOLVED);
                assertThat(incident.getResolvedAt()).isAfterOrEqualTo(incident.getStartedAt());
            });
            assertThat(fourth.getBean(MonitoredServiceRepository.class).findById(serviceId).orElseThrow()
                    .getConsecutiveFailures()).isZero();
            assertThat(fourth.getBean(CheckHistoryService.class).history(serviceId).orElseThrow()).hasSize(5);
        }
    }

    private void record(ConfigurableApplicationContext context, long serviceId, HealthStatus status) {
        var service = context.getBean(MonitoredServiceRepository.class).findById(serviceId).orElseThrow();
        context.getBean(CheckResultService.class).record(service,
                new HealthCheckResponse(serviceId, service.getName(), service.getUrl(), status,
                        status == HealthStatus.UP ? 200 : 503, 10, Instant.now()));
    }

    private ConfigurableApplicationContext start(Path database) {
        return new SpringApplicationBuilder(ServicePulseApplication.class)
                .web(WebApplicationType.NONE)
                .run("--spring.datasource.url=jdbc:h2:file:" + database.toAbsolutePath().toString().replace('\\', '/'),
                        "--servicepulse.monitoring.enabled=false");
    }
}
